// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LayBody: typeof import('@layui/layui-vue')['LayBody']
    LayBreadcrumb: typeof import('@layui/layui-vue')['LayBreadcrumb']
    LayBreadcrumbItem: typeof import('@layui/layui-vue')['LayBreadcrumbItem']
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayCheckbox: typeof import('@layui/layui-vue')['LayCheckbox']
    LayConfigProvider: typeof import('@layui/layui-vue')['LayConfigProvider']
    LayDatePicker: typeof import('@layui/layui-vue')['LayDatePicker']
    LayDropdown: typeof import('@layui/layui-vue')['LayDropdown']
    LayDropdownMenu: typeof import('@layui/layui-vue')['LayDropdownMenu']
    LayDropdownMenuItem: typeof import('@layui/layui-vue')['LayDropdownMenuItem']
    LayField: typeof import('@layui/layui-vue')['LayField']
    LayFooter: typeof import('@layui/layui-vue')['LayFooter']
    LayForm: typeof import('@layui/layui-vue')['LayForm']
    LayFormItem: typeof import('@layui/layui-vue')['LayFormItem']
    LayFullscreen: typeof import('@layui/layui-vue')['LayFullscreen']
    LayHeader: typeof import('@layui/layui-vue')['LayHeader']
    LayIcon: typeof import('@layui/icons-vue')['LayIcon']
    LayInput: typeof import('@layui/layui-vue')['LayInput']
    LayInputNumber: typeof import('@layui/layui-vue')['LayInputNumber']
    LayLayer: typeof import('@layui/layer-vue')['LayLayer']
    LayLayout: typeof import('@layui/layui-vue')['LayLayout']
    LayLine: typeof import('@layui/layui-vue')['LayLine']
    LayLogo: typeof import('@layui/layui-vue')['LayLogo']
    LayMenu: typeof import('@layui/layui-vue')['LayMenu']
    LayMenuItem: typeof import('@layui/layui-vue')['LayMenuItem']
    LayPanel: typeof import('@layui/layui-vue')['LayPanel']
    LayPopconfirm: typeof import('@layui/layui-vue')['LayPopconfirm']
    LayRadio: typeof import('@layui/layui-vue')['LayRadio']
    LayRadioButton: typeof import('@layui/layui-vue')['LayRadioButton']
    LayRadioGroup: typeof import('@layui/layui-vue')['LayRadioGroup']
    LaySelect: typeof import('@layui/layui-vue')['LaySelect']
    LaySelectOption: typeof import('@layui/layui-vue')['LaySelectOption']
    LaySide: typeof import('@layui/layui-vue')['LaySide']
    LaySplitPanel: typeof import('@layui/layui-vue')['LaySplitPanel']
    LaySubMenu: typeof import('@layui/layui-vue')['LaySubMenu']
    LaySwitch: typeof import('@layui/layui-vue')['LaySwitch']
    LayTab: typeof import('@layui/layui-vue')['LayTab']
    LayTabItem: typeof import('@layui/layui-vue')['LayTabItem']
    LayTable: typeof import('@layui/layui-vue')['LayTable']
    LayTag: typeof import('@layui/layui-vue')['LayTag']
    LayTextarea: typeof import('@layui/layui-vue')['LayTextarea']
    LayTree: typeof import('@layui/layui-vue')['LayTree']
    LayTreeSelect: typeof import('@layui/layui-vue')['LayTreeSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
